name: deploy-web-stage
on:
  push:
    branches: master
env:
  ENVIRONMENT: stage
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      WEBSITE_BUCKET: web-app-name
      AWS_DEFAULT_REGION: eu-west-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Set yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - run: yarn
      - run: npx expo-optimize
      - run: npx expo build:web --no-pwa
      - run: aws s3 sync ./web-build s3://${WEBSITE_BUCKET}-${ENVIRONMENT} --delete
